- name: Sample Playbook linux
  hosts: all
  gather_facts: false
  tasks:
     - name: ping test
       ping:
       register: ping_op
     - debug:
         var: ping_op
     - name: copy file
       shell:
           |
         ps -ef
       register: s_op
     - debug: 
          var: s_op
