- name: Sample Playbook linux
  hosts: all
  gather_facts: false
  tasks:
     - name: ping test
       ping:
       register: ping_op
     - debug:
         var: ping_op
     - name: fetch the users
       shell:
           |
         cat /etc/passwd
       register: user_op
     - debug: 
          var: user_op.stdout
