---
  - name: Windows sample playbook
    hosts: all
    gather_facts: true
    tasks:
      - name: ping_test
        win_ping:
        register: win_ping
      - debug:
          var: win_ping
      - win_shell:
             |
           $CompObject =  Get-WmiObject -Class WIN32_OperatingSystem
           $Memory = ((($CompObject.TotalVisibleMemorySize - $CompObject.FreePhysicalMemory)*100)/ $CompObject.TotalVisibleMemorySize)
           Write-Host "Memory usage in Percentage:" $Memory
           # Top 5 process Memory Usage (MB)
           $processMemoryUsage = Get-WmiObject WIN32_PROCESS | Sort-Object -Property ws -Descending | Select-Object -first 5 processname, @{Name="Mem Usage(MB)";Expression={[math]::round($_.ws / 1mb)}}
           $processMemoryUsage
        register: mem_op
      - debug: 
          var: mem_op.stdout_lines
