---
  - name: Windows sample playbook
    hosts: all
    gather_facts: true
    tasks:
      - name: ping_test
        win_ping:
        register: win_ping
      - debug:
          var: win_ping
      - name: copy file
        copy:
         src: "{{ source_dest }}"
         dest: "{{ dest_loc }}"
